image: python:3.7

variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

stages:
  - tests
  - system test

before_script:
  - date
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - python3 -m pip install -r setup/requirements/requirements.txt
  - python3 -m pip install -r setup/requirements/dev-requirements.txt

pytest:
  stage: tests
  script:
    - cd wizer/tests/
    - python3 -m pytest unit_tests -v
    - python3 -m pytest integration_tests -v

django:
  stage: tests
  artifacts:
    paths:
      - db.sqlite3
    expire_in: 1 day
  script:
    - python3 manage.py collectstatic --noinput
    - python3 manage.py check
    - python3 manage.py migrate

end2end:
  stage: system test
  script:
    - python3 -m pytest wizer/tests/end2end -vvs